version: 2.1

jobs:
  bundle_on_2_2:
    parameters:
      x:
        type: string
    docker:
      - image: circleci/ruby:2.2
    steps:
      - checkout
      - run: bundle install --verbose

workflows:
  build:
    jobs:
      - bundle_on_2_2:
          x: "00"
      - bundle_on_2_2:
          x: "01"
      - bundle_on_2_2:
          x: "02"
      - bundle_on_2_2:
          x: "03"
      - bundle_on_2_2:
          x: "04"
      - bundle_on_2_2:
          x: "05"
      - bundle_on_2_2:
          x: "06"
      - bundle_on_2_2:
          x: "07"
      - bundle_on_2_2:
          x: "08"
      - bundle_on_2_2:
          x: "09"
      - bundle_on_2_2:
          x: "10"
      - bundle_on_2_2:
          x: "11"
      - bundle_on_2_2:
          x: "12"
      - bundle_on_2_2:
          x: "13"
      - bundle_on_2_2:
          x: "14"
      - bundle_on_2_2:
          x: "15"
      - bundle_on_2_2:
          x: "16"
      - bundle_on_2_2:
          x: "17"
      - bundle_on_2_2:
          x: "18"
      - bundle_on_2_2:
          x: "19"
      - bundle_on_2_2:
          x: "20"
      - bundle_on_2_2:
          x: "21"
      - bundle_on_2_2:
          x: "22"
      - bundle_on_2_2:
          x: "23"
      - bundle_on_2_2:
          x: "24"
      - bundle_on_2_2:
          x: "25"
      - bundle_on_2_2:
          x: "26"
      - bundle_on_2_2:
          x: "27"
      - bundle_on_2_2:
          x: "28"
      - bundle_on_2_2:
          x: "29"
      - bundle_on_2_2:
          x: "30"
      - bundle_on_2_2:
          x: "31"
      - bundle_on_2_2:
          x: "32"
      - bundle_on_2_2:
          x: "33"
      - bundle_on_2_2:
          x: "34"
      - bundle_on_2_2:
          x: "35"
      - bundle_on_2_2:
          x: "36"
      - bundle_on_2_2:
          x: "37"
      - bundle_on_2_2:
          x: "38"
      - bundle_on_2_2:
          x: "39"
      - bundle_on_2_2:
          x: "40"
      - bundle_on_2_2:
          x: "41"
      - bundle_on_2_2:
          x: "42"
      - bundle_on_2_2:
          x: "43"
      - bundle_on_2_2:
          x: "44"
      - bundle_on_2_2:
          x: "45"
      - bundle_on_2_2:
          x: "46"
      - bundle_on_2_2:
          x: "47"
      - bundle_on_2_2:
          x: "48"
      - bundle_on_2_2:
          x: "49"
      - bundle_on_2_2:
          x: "50"
      - bundle_on_2_2:
          x: "51"
      - bundle_on_2_2:
          x: "52"
      - bundle_on_2_2:
          x: "53"
      - bundle_on_2_2:
          x: "54"
      - bundle_on_2_2:
          x: "55"
      - bundle_on_2_2:
          x: "56"
      - bundle_on_2_2:
          x: "57"
      - bundle_on_2_2:
          x: "58"
      - bundle_on_2_2:
          x: "59"
      - bundle_on_2_2:
          x: "60"
      - bundle_on_2_2:
          x: "61"
      - bundle_on_2_2:
          x: "62"
      - bundle_on_2_2:
          x: "63"
      - bundle_on_2_2:
          x: "64"
      - bundle_on_2_2:
          x: "65"
      - bundle_on_2_2:
          x: "66"
      - bundle_on_2_2:
          x: "67"
      - bundle_on_2_2:
          x: "68"
      - bundle_on_2_2:
          x: "69"
      - bundle_on_2_2:
          x: "70"
      - bundle_on_2_2:
          x: "71"
      - bundle_on_2_2:
          x: "72"
      - bundle_on_2_2:
          x: "73"
      - bundle_on_2_2:
          x: "74"
      - bundle_on_2_2:
          x: "75"
      - bundle_on_2_2:
          x: "76"
      - bundle_on_2_2:
          x: "77"
      - bundle_on_2_2:
          x: "78"
      - bundle_on_2_2:
          x: "79"
      - bundle_on_2_2:
          x: "80"
      - bundle_on_2_2:
          x: "81"
      - bundle_on_2_2:
          x: "82"
      - bundle_on_2_2:
          x: "83"
      - bundle_on_2_2:
          x: "84"
      - bundle_on_2_2:
          x: "85"
      - bundle_on_2_2:
          x: "86"
      - bundle_on_2_2:
          x: "87"
      - bundle_on_2_2:
          x: "88"
      - bundle_on_2_2:
          x: "89"
      - bundle_on_2_2:
          x: "90"
      - bundle_on_2_2:
          x: "91"
      - bundle_on_2_2:
          x: "92"
      - bundle_on_2_2:
          x: "93"
      - bundle_on_2_2:
          x: "94"
      - bundle_on_2_2:
          x: "95"
      - bundle_on_2_2:
          x: "96"
      - bundle_on_2_2:
          x: "97"
      - bundle_on_2_2:
          x: "98"
      - bundle_on_2_2:
          x: "99"
      - bundle_on_2_2:
          x: "100"
      - bundle_on_2_2:
          x: "101"
      - bundle_on_2_2:
          x: "102"
      - bundle_on_2_2:
          x: "103"
      - bundle_on_2_2:
          x: "104"
      - bundle_on_2_2:
          x: "105"
      - bundle_on_2_2:
          x: "106"
      - bundle_on_2_2:
          x: "107"
      - bundle_on_2_2:
          x: "108"
      - bundle_on_2_2:
          x: "109"
      - bundle_on_2_2:
          x: "110"
      - bundle_on_2_2:
          x: "111"
      - bundle_on_2_2:
          x: "112"
      - bundle_on_2_2:
          x: "113"
      - bundle_on_2_2:
          x: "114"
      - bundle_on_2_2:
          x: "115"
      - bundle_on_2_2:
          x: "116"
      - bundle_on_2_2:
          x: "117"
      - bundle_on_2_2:
          x: "118"
      - bundle_on_2_2:
          x: "119"
      - bundle_on_2_2:
          x: "120"
      - bundle_on_2_2:
          x: "121"
      - bundle_on_2_2:
          x: "122"
      - bundle_on_2_2:
          x: "123"
      - bundle_on_2_2:
          x: "124"
      - bundle_on_2_2:
          x: "125"
      - bundle_on_2_2:
          x: "126"
      - bundle_on_2_2:
          x: "127"
      - bundle_on_2_2:
          x: "128"
      - bundle_on_2_2:
          x: "129"
      - bundle_on_2_2:
          x: "130"
      - bundle_on_2_2:
          x: "131"
      - bundle_on_2_2:
          x: "132"
      - bundle_on_2_2:
          x: "133"
      - bundle_on_2_2:
          x: "134"
      - bundle_on_2_2:
          x: "135"
      - bundle_on_2_2:
          x: "136"
      - bundle_on_2_2:
          x: "137"
      - bundle_on_2_2:
          x: "138"
      - bundle_on_2_2:
          x: "139"
      - bundle_on_2_2:
          x: "140"
      - bundle_on_2_2:
          x: "141"
      - bundle_on_2_2:
          x: "142"
      - bundle_on_2_2:
          x: "143"
      - bundle_on_2_2:
          x: "144"
      - bundle_on_2_2:
          x: "145"
      - bundle_on_2_2:
          x: "146"
      - bundle_on_2_2:
          x: "147"
      - bundle_on_2_2:
          x: "148"
      - bundle_on_2_2:
          x: "149"
      - bundle_on_2_2:
          x: "150"
      - bundle_on_2_2:
          x: "151"
      - bundle_on_2_2:
          x: "152"
      - bundle_on_2_2:
          x: "153"
      - bundle_on_2_2:
          x: "154"
      - bundle_on_2_2:
          x: "155"
      - bundle_on_2_2:
          x: "156"
      - bundle_on_2_2:
          x: "157"
      - bundle_on_2_2:
          x: "158"
      - bundle_on_2_2:
          x: "159"
      - bundle_on_2_2:
          x: "160"
      - bundle_on_2_2:
          x: "161"
      - bundle_on_2_2:
          x: "162"
      - bundle_on_2_2:
          x: "163"
      - bundle_on_2_2:
          x: "164"
      - bundle_on_2_2:
          x: "165"
      - bundle_on_2_2:
          x: "166"
      - bundle_on_2_2:
          x: "167"
      - bundle_on_2_2:
          x: "168"
      - bundle_on_2_2:
          x: "169"
      - bundle_on_2_2:
          x: "170"
      - bundle_on_2_2:
          x: "171"
      - bundle_on_2_2:
          x: "172"
      - bundle_on_2_2:
          x: "173"
      - bundle_on_2_2:
          x: "174"
      - bundle_on_2_2:
          x: "175"
      - bundle_on_2_2:
          x: "176"
      - bundle_on_2_2:
          x: "177"
      - bundle_on_2_2:
          x: "178"
      - bundle_on_2_2:
          x: "179"
      - bundle_on_2_2:
          x: "180"
      - bundle_on_2_2:
          x: "181"
      - bundle_on_2_2:
          x: "182"
      - bundle_on_2_2:
          x: "183"
      - bundle_on_2_2:
          x: "184"
      - bundle_on_2_2:
          x: "185"
      - bundle_on_2_2:
          x: "186"
      - bundle_on_2_2:
          x: "187"
      - bundle_on_2_2:
          x: "188"
      - bundle_on_2_2:
          x: "189"
      - bundle_on_2_2:
          x: "190"
      - bundle_on_2_2:
          x: "191"
      - bundle_on_2_2:
          x: "192"
      - bundle_on_2_2:
          x: "193"
      - bundle_on_2_2:
          x: "194"
      - bundle_on_2_2:
          x: "195"
      - bundle_on_2_2:
          x: "196"
      - bundle_on_2_2:
          x: "197"
      - bundle_on_2_2:
          x: "198"
      - bundle_on_2_2:
          x: "199"
