version: 2

jruby_env: &jruby_env
  # By default we have 2 CPUs and 4GB ram available
  # https://circleci.com/docs/2.0/configuration-reference/#resource_class
  JRUBY_OPTS: "--debug -J-Xmn1024m -J-Xms2048m -J-Xmx2048m"

common_env: &common_env
  # CircleCI container has two cores, but Ruby can see 32 cores. So we
  # configure test-queue.
  # See https://github.com/tmm1/test-queue#environment-variables
  TEST_QUEUE_WORKERS: 2

spec_steps: &spec_steps
  - checkout
  - run: bundle install
  - run: COVERAGE=true bundle exec rake spec

spec_steps_no_coverage: &spec_steps_no_coverage
  - checkout
  - run: bundle install
  - run: bundle exec rake spec

ascii_spec_steps: &ascii_spec_steps
  - checkout
  - run: bundle install
  - run: bundle exec rake ascii_spec

jobs:

  # Ruby 2.2
  ruby-2.2-spec:
    docker:
      - image: circleci/ruby:2.2
    environment:
      <<: *common_env
    steps:
      *spec_steps
  ruby-2.2-spec-no-coverage:
    docker:
      - image: circleci/ruby:2.2
    environment:
      <<: *common_env
    steps:
      *spec_steps_no_coverage
  ruby-2.2-ascii_spec:
    docker:
      - image: circleci/ruby:2.2
    environment:
      <<: *common_env
    steps:
      *ascii_spec_steps

  # Ruby 2.3
  ruby-2.3-spec:
    docker:
      - image: circleci/ruby:2.3
    environment:
      <<: *common_env
    steps:
      *spec_steps
  ruby-2.3-spec-no-coverage:
    docker:
      - image: circleci/ruby:2.3
    environment:
      <<: *common_env
    steps:
      *spec_steps_no_coverage
  ruby-2.3-ascii_spec:
    docker:
      - image: circleci/ruby:2.3
    environment:
      <<: *common_env
    steps:
      *ascii_spec_steps

  # Ruby 2.4
  ruby-2.4-spec:
    docker:
      - image: circleci/ruby:2.4
    environment:
      <<: *common_env
    steps:
      *spec_steps
  ruby-2.4-spec-no-coverage:
    docker:
      - image: circleci/ruby:2.4
    environment:
      <<: *common_env
    steps:
      *spec_steps_no_coverage
  ruby-2.4-ascii_spec:
    docker:
      - image: circleci/ruby:2.4
    environment:
      <<: *common_env
    steps:
      *ascii_spec_steps

  # Ruby 2.5
  ruby-2.5-spec:
    docker:
      - image: circleci/ruby:2.5
    environment:
      <<: *common_env
    steps:
      *spec_steps
  ruby-2.5-spec-no-coverage:
    docker:
      - image: circleci/ruby:2.5
    environment:
      <<: *common_env
    steps:
      *spec_steps_no_coverage
  ruby-2.5-ascii_spec:
    docker:
      - image: circleci/ruby:2.5
    environment:
      <<: *common_env
    steps:
      *ascii_spec_steps

  # Ruby 2.6
  ruby-2.6-spec:
    docker:
      - image: circleci/ruby:2.6
    environment:
      <<: *common_env
    steps:
      *spec_steps
  ruby-2.6-spec-no-coverage:
    docker:
      - image: circleci/ruby:2.6
    environment:
      <<: *common_env
    steps:
      *spec_steps_no_coverage
  ruby-2.6-ascii_spec:
    docker:
      - image: circleci/ruby:2.6
    environment:
      <<: *common_env
    steps:
      *ascii_spec_steps

  # ruby-head (nightly snapshot build)
  ruby-head-spec:
    docker:
      - image: rubocophq/circleci-ruby-snapshot:latest
    environment:
      <<: *common_env
    steps:
      *spec_steps
  ruby-head-spec-no-coverage:
    docker:
      - image: rubocophq/circleci-ruby-snapshot:latest
    environment:
      <<: *common_env
    steps:
      *spec_steps_no_coverage
  ruby-head-ascii_spec:
    docker:
      - image: rubocophq/circleci-ruby-snapshot:latest
    environment:
      <<: *common_env
    steps:
      *ascii_spec_steps

  # JRuby 9.2
  jruby-9.2-spec:
    docker:
      - image: circleci/jruby:9.2
    environment:
      <<: *common_env
      <<: *jruby_env
    steps:
      *spec_steps
  jruby-9.2-spec-no-coverage:
    docker:
      - image: circleci/jruby:9.2
    environment:
      <<: *common_env
      <<: *jruby_env
    steps:
      *spec_steps_no_coverage
  jruby-9.2-ascii_spec:
    docker:
      - image: circleci/jruby:9.2
    environment:
      <<: *common_env
      <<: *jruby_env
    steps:
      *ascii_spec_steps

workflows:
  version: 2
  build:
    jobs:

      - ruby-2.2-spec
      - ruby-2.2-spec-no-coverage
      - ruby-2.2-ascii_spec

      - ruby-2.3-spec
      - ruby-2.3-spec-no-coverage
      - ruby-2.3-ascii_spec

      - ruby-2.4-spec
      - ruby-2.4-spec-no-coverage
      - ruby-2.4-ascii_spec

      - ruby-2.5-spec
      - ruby-2.5-spec-no-coverage
      - ruby-2.5-ascii_spec

      - ruby-2.6-spec
      - ruby-2.6-spec-no-coverage
      - ruby-2.6-ascii_spec

      - ruby-head-spec
      - ruby-head-spec-no-coverage
      - ruby-head-ascii_spec

      - jruby-9.2-spec
      - jruby-9.2-spec-no-coverage
      - jruby-9.2-ascii_spec
