version: 2

jobs:

  none:
    docker:
      - image: circleci/jruby:9.2
    environment:
      JRUBY_OPTS: "-J-Xmn1024m -J-Xms2048m -J-Xmx2048m"
      TEST_QUEUE_WORKERS: 2
    steps:
      - run: echo $JRUBY_OPTS
      - checkout
      - run: bundle install
      - run: bundle exec rake spec
      - run: bundle exec rake ascii_spec
      - run: bundle exec rake internal_investigation
  dev:
    docker:
      - image: circleci/jruby:9.2
    environment:
      JRUBY_OPTS: "--dev -J-Xmn1024m -J-Xms2048m -J-Xmx2048m"
      TEST_QUEUE_WORKERS: 2
    steps:
      - run: echo $JRUBY_OPTS
      - checkout
      - run: bundle install
      - run: bundle exec rake spec
      - run: bundle exec rake ascii_spec
      - run: bundle exec rake internal_investigation
  debug:
    docker:
      - image: circleci/jruby:9.2
    environment:
      JRUBY_OPTS: "--debug -J-Xmn1024m -J-Xms2048m -J-Xmx2048m"
      TEST_QUEUE_WORKERS: 2
    steps:
      - run: echo $JRUBY_OPTS
      - checkout
      - run: bundle install
      - run: bundle exec rake spec
      - run: bundle exec rake ascii_spec
      - run: bundle exec rake internal_investigation
  dev_and_debug:
    docker:
      - image: circleci/jruby:9.2
    environment:
      JRUBY_OPTS: "--dev --debug -J-Xmn1024m -J-Xms2048m -J-Xmx2048m"
      TEST_QUEUE_WORKERS: 2
    steps:
      - run: echo $JRUBY_OPTS
      - checkout
      - run: bundle install
      - run: bundle exec rake spec
      - run: bundle exec rake ascii_spec
      - run: bundle exec rake internal_investigation
  none_with_coverage:
    docker:
      - image: circleci/jruby:9.2
    environment:
      JRUBY_OPTS: "-J-Xmn1024m -J-Xms2048m -J-Xmx2048m"
      TEST_QUEUE_WORKERS: 2
    steps:
      - run: echo $JRUBY_OPTS
      - checkout
      - run: bundle install
      - run: COVERAGE=true bundle exec rake spec
      - run: bundle exec rake ascii_spec
      - run: bundle exec rake internal_investigation
  dev_with_coverage:
    docker:
      - image: circleci/jruby:9.2
    environment:
      JRUBY_OPTS: "--dev -J-Xmn1024m -J-Xms2048m -J-Xmx2048m"
      TEST_QUEUE_WORKERS: 2
    steps:
      - run: echo $JRUBY_OPTS
      - checkout
      - run: bundle install
      - run: COVERAGE=true bundle exec rake spec
      - run: bundle exec rake ascii_spec
      - run: bundle exec rake internal_investigation
  debug_with_coverage:
    docker:
      - image: circleci/jruby:9.2
    environment:
      JRUBY_OPTS: "--debug -J-Xmn1024m -J-Xms2048m -J-Xmx2048m"
      TEST_QUEUE_WORKERS: 2
    steps:
      - run: echo $JRUBY_OPTS
      - checkout
      - run: bundle install
      - run: COVERAGE=true bundle exec rake spec
      - run: bundle exec rake ascii_spec
      - run: bundle exec rake internal_investigation
  dev_and_debug_with_coverage:
    docker:
      - image: circleci/jruby:9.2
    environment:
      JRUBY_OPTS: "--dev --debug -J-Xmn1024m -J-Xms2048m -J-Xmx2048m"
      TEST_QUEUE_WORKERS: 2
    steps:
      - run: echo $JRUBY_OPTS
      - checkout
      - run: bundle install
      - run: COVERAGE=true bundle exec rake spec
      - run: bundle exec rake ascii_spec
      - run: bundle exec rake internal_investigation

workflows:
  version: 2
  build:
    jobs:
      - none
      - dev
      - debug
      - dev_and_debug
      - none_with_coverage
      - dev_with_coverage
      - debug_with_coverage
      - dev_and_debug_with_coverage
