version: 2

jruby_env: &jruby_env
  # By default we have 2 CPUs and 4GB ram available
  # https://circleci.com/docs/2.0/configuration-reference/#resource_class
  JRUBY_OPTS: "--debug -J-Xmn1024m -J-Xms2048m -J-Xmx2048m"

common_env: &common_env
  # CircleCI container has two cores, but Ruby can see 32 cores. So we
  # configure test-queue.
  # See https://github.com/tmm1/test-queue#environment-variables
  TEST_QUEUE_WORKERS: 2

spec_steps_no_coverage: &spec_steps_no_coverage
  - checkout
  - run: bundle install
  - run: bundle exec rspec

spec_steps_with_coverage: &spec_steps_with_coverage
  - checkout
  - run: bundle install
  - run: COVERAGE=true bundle exec rspec

jobs:

  # Ruby 2.2
  no-cov-2.2:
    docker:
      - image: circleci/ruby:2.2
    environment:
      <<: *common_env
    steps:
      *spec_steps_no_coverage
  with-cov-2.2:
    docker:
      - image: circleci/ruby:2.2
    environment:
      <<: *common_env
    steps:
      *spec_steps_with_coverage

  # Ruby 2.3
  no-cov-2.3:
    docker:
      - image: circleci/ruby:2.3
    environment:
      <<: *common_env
    steps:
      *spec_steps_no_coverage
  with-cov-2.3:
    docker:
      - image: circleci/ruby:2.3
    environment:
      <<: *common_env
    steps:
      *spec_steps_with_coverage

  # Ruby 2.4
  no-cov-2.4:
    docker:
      - image: circleci/ruby:2.4
    environment:
      <<: *common_env
    steps:
      *spec_steps_no_coverage
  with-cov-2.4:
    docker:
      - image: circleci/ruby:2.4
    environment:
      <<: *common_env
    steps:
      *spec_steps_with_coverage

  # Ruby 2.5
  no-cov-2.5:
    docker:
      - image: circleci/ruby:2.5
    environment:
      <<: *common_env
    steps:
      *spec_steps_no_coverage
  with-cov-2.5:
    docker:
      - image: circleci/ruby:2.5
    environment:
      <<: *common_env
    steps:
      *spec_steps_with_coverage

  # Ruby 2.6
  no-cov-2.6:
    docker:
      - image: circleci/ruby:2.6
    environment:
      <<: *common_env
    steps:
      *spec_steps_no_coverage
  with-cov-2.6:
    docker:
      - image: circleci/ruby:2.6
    environment:
      <<: *common_env
    steps:
      *spec_steps_with_coverage

  # ruby-head (nightly snapshot build)
  no-cov-head:
    docker:
      - image: rubocophq/circleci-ruby-snapshot:latest
    environment:
      <<: *common_env
    steps:
      *spec_steps_no_coverage
  with-cov-head:
    docker:
      - image: rubocophq/circleci-ruby-snapshot:latest
    environment:
      <<: *common_env
    steps:
      *spec_steps_with_coverage

  # JRuby 9.2
  no-cov-jruby:
    docker:
      - image: circleci/jruby:9.2
    environment:
      <<: *common_env
      <<: *jruby_env
    steps:
      *spec_steps_no_coverage
  with-cov-jruby:
    docker:
      - image: circleci/jruby:9.2
    environment:
      <<: *common_env
      <<: *jruby_env
    steps:
      *spec_steps_with_coverage

workflows:
  version: 2
  build:
    jobs:
      - no-cov-2.2
      - no-cov-2.3
      - no-cov-2.4
      - no-cov-2.5
      - no-cov-2.6
      - no-cov-head
      - no-cov-jruby
      - with-cov-2.2
      - with-cov-2.3
      - with-cov-2.4
      - with-cov-2.5
      - with-cov-2.6
      - with-cov-head
      - with-cov-jruby
